name: Build Check

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create .env File
        uses: 'DamianReeves/write-file-action@master'
        with:
          path: ./.env
          write-mode: overwrite
          contents: ${{ secrets.ENV_FILE }}

      - name: Install NPM dependencies
        run: npm install

      - name: Generate static files
        run: npm run build
